version: '3'
services:
  docker:
    privileged: true
    image: docker:dind
    ports:
    - 8081:8081
  cluster:
    build: ./cluster
    # volumes:
    # - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8022:8022
    environment:
    - DOCKER_HOST=tcp://docker:2375
    depends_on:
    - docker
