version: '3.5'
networks:
  default:
    name: dev
services:

  docker:
    privileged: true
    build: ./docker
    stop_grace_period: 1s
    ports:
    - "8081:8081"
    volumes:
    - ./docker/daemon.json:/etc/docker/daemon.json
    - ./docker/images/preload:/preload
    # - type: "bind"
    #   source: ./registry/certs/domain.crt
    #   target: /etc/docker/certs.d/registry:443/ca.crt

  registry:
    image: registry:2
    expose:
    - "443"
    volumes:
    - ./registry/data:/var/lib/registry
    # - ./registry/certs:/certs
    environment:
    - REGISTRY_HTTP_ADDR=0.0.0.0:443
    # - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
    # - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    depends_on:
    - docker

  cluster:
    build: ./cluster
    stop_grace_period: 1s
    volumes:
    - ./docker/images:/setup/images
    expose:
    - "8022"
    ports:
    - "8022:8022"
    # - "5901:5901"
    environment:
    - DOCKER_HOST=tcp://docker:2375
    - WORKERS=0
    depends_on:
    - registry

  gateway:
    build: ./gateway
    stop_grace_period: 1s
    environment:
    - INLETS_TOKEN
    - INLETS_REMOTE
    - INLETS_DOMAIN
    - INLETS_PREFIX
    depends_on:
    - cluster

  machine1: &machine
    build:
      context: ./cluster
      args:
        MODE: machine
    stop_grace_period: 1s
    expose:
    - "8022"
    # ports:
    # - "50122:8022"
    environment:
    - DOCKER_HOST=tcp://docker:2375
    depends_on:
    - gateway

  machine2: 
    <<: *machine
    # ports:
    # - "50222:8022"
  machine3: *machine
  machine4: *machine
  machine5: *machine
  machine6: *machine
  machine7: *machine
  machine8: *machine
  machine9: *machine
  machine10: *machine
  machine11: *machine
  machine12: *machine
  machine13: *machine
  machine14: *machine
  machine15: *machine
  machine16: *machine
  machine17: *machine
  machine18: *machine
  machine19: *machine
  machine20: *machine
