version: '3'
services:
  docker:
    privileged: true
    image: docker:dind
    stop_grace_period: 1s
    ports:
    - "8081:8081"
    volumes:
    - ./docker/images/preload:/preload
  cluster:
    build: ./cluster
    stop_grace_period: 1s
    volumes:
    - ./docker/images:/setup/images
    ports:
    - "8022:8022"
    environment:
    - DOCKER_HOST=tcp://docker:2375
    - WORKERS=0
    depends_on:
    - docker
