version: '3.5'
networks:
  default:
    name: k8s
services:

  cluster:
    # privileged: true
    build: ./cluster
    volumes:
    # - ./data/docker:/var/lib/docker
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8022:8022
    - 8080:80
