apiVersion: v1
kind: Pod
metadata:
  name: script2
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name: cmd
    image: debian:stretch-slim
    command:
    - "bash"
    - "-c"
    - "while true; do date; sleep 5; done"
